### PR TITLE
Fix incorrect and incomplete activity data in Solid PREP responses

### LINKED ISSUE #1799: Incorrect and incomplete Add activity data in Solid PREP responses
Looking into implementing Solid PREP in dokieli. Cool stuff! Some bugs with the response data but they seem relatively minor.

Request (snippet):

```
$ curl -ki -H'Accept-Events: "prep"; accept="application/ld+json"' https://csarven.localhost:8443/dokieli/inbox/
```

Response (snippet):

```
HTTP/1.1 200 OK
X-Powered-By: solid-server/5.7.11
Accept-Events: "prep";accept=("message/rfc822" "application/ld+json" "text/turtle")
Events: protocol="prep", status=200, expires="Thu, 07 Nov 2024 15:13:48 GMT"
Content-Type: multipart/mixed; boundary="MAJ8bCuGxmcu9HkCOzUi"

--MAJ8bCuGxmcu9HkCOzUi
Content-Type: text/turtle

@prefix : <#>.
@prefix dct: <http://purl.org/dc/terms/>.
@prefix ldp: <http://www.w3.org/ns/ldp#>.
@prefix stat: <http://www.w3.org/ns/posix/stat#>.
@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.
@prefix inbox: <>.
@prefix tur: <http://www.w3.org/ns/iana/media-types/text/turtle#>.

inbox:
    a ldp:BasicContainer, ldp:Container;
    dct:modified "2024-11-07T14:02:25Z"^^xsd:dateTime;
    ldp:contains
        <c86da0c8-087b-4d56-8c52-5cb682c07fe6.ttl>,
        <eb60ab84-80a5-4cd2-adf3-acc7a15180b4.ttl>,
        <eca044ed-c8b7-46fd-a469-c895df0ecd84.ttl>;
    stat:mtime 1730988145.945;
    stat:size 4096 .


--A+1x55W+mvT60TuzH1n5
Content-Type: application/ld+json

{
  "published": "Thu, 07 Nov 2024 14:15:58 GMT",
  "type": "Add",
  "object": "https://csarven.localhost/dokieli/inbox/",
  "target": "/dokieli/inbox/fa6ec1e0-dd3f-4b1f-b915-6dc3311351af.ttl",
  "state": "W/\"7-rM9AyJuqT6iOan/xHh+AW+7K/T8\"",
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    "https://www.w3.org/ns/solid/notification/v1"
  ]
}
```

Note that the initial response is in `text/turtle`. Should that be `application/ld+json`?

Note the date format for `as:published` should have range in `xsd:dateTime`. Issue: NSS should convert the date format.

---

Another request (snippet):

```
$ curl -ki -H'Accept-Events: "prep"; accept="text/turtle"' https://csarven.localhost:8443/dokieli/inbox/
```

Response Headers
```
HTTP/1.1 200 OK
X-Powered-By: solid-server/5.7.11
Accept-Events: "prep";accept=("message/rfc822" "application/ld+json" "text/turtle")
Events: protocol="prep", status=200, expires="Thu, 07 Nov 2024 14:57:57 GMT"
Content-Type: multipart/mixed; boundary="KQman1p0csYxoyFdjhR2"
```

Notification
```
--chmdPhxmuTFKwWBW6gL2
Content-Type: text/turtle

@prefix as: <https://www.w3.org/ns/activitystreams#> .
@prefix notify: <https://www.w3.org/ns/solid/notification/v1#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<undefined> a as:Add ;
    notify:state "W/"7-rM9AyJuqT6iOan/xHh+AW+7K/T8"" ;
    as:object https://csarven.localhost/dokieli/inbox/ ;
    as:published "Thu, 07 Nov 2024 14:02:25 GMT"^^xsd:dateTime .
```

Note also data format here. Note `undefined` in subject IRI. Should probably be an http UUID if they can be eventually dereference but bnode with a UUID would do as well. The data also seems to be incomplete compared to response in `application/ld+json`.

---

I think the description of Add also needs a minor fix; swap object and target values. Taking the JSON-LD example from above, it should be like this:

```
{
  "id": "http://example.com/.well-known/genid/0798c962-1879-448f-af44-f83162a029be",
  "published": "2024-11-07T14:15:58Z",
  "type": "Add",
  "object": "/dokieli/inbox/fa6ec1e0-dd3f-4b1f-b915-6dc3311351af.ttl",
  "target": "https://csarven.localhost/dokieli/inbox/",
  "state": "W/\"7-rM9AyJuqT6iOan/xHh+AW+7K/T8\"",
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    "https://www.w3.org/ns/solid/notification/v1"
  ]
}
```

### PR DESCRIPTION
**Pull request by CxRes**
Fixes #1799

### CODE REVIEW

File: lib/handlers/notify.js [hunk 1]
```diff
@@ -38,18 +38,32 @@ function getParentActivity (method, status) {
...
+function getDate (date) {
+  if (date) {
+    const eventDate = new Date(date)
+    if (!isNaN(eventDate.valueOf())) {
+      return filterMillseconds(eventDate.toISOString())
+    }
+  }
+  const now = new Date()
+  return filterMillseconds(now.toISOString())
+}
```
Comment (csarven) [inline lib/handlers/notify.js:54]: Why filterMillseconds? Is it because that information is not actually available in value used for the Date / Last-Modified headers or it defaults to 000? (If elsewhere that information is available, it'd be preferable to not drop it.

File: lib/rdf-notification-template.js [hunk 2]
```diff
@@ -13,30 +15,40 @@ function generateJSONNotification ({
...
+  }
 
   return `@prefix as: <${CONTEXT_ACTIVITYSTREAMS}#> .
 @prefix notify: <${CONTEXT_NOTIFICATION}#> .
 @prefix xsd: <${CONTEXT_XML_SCHEMA}#> .
 
-<${eventId}> a as:${activity} ;${state && stateLine}
-    as:object ${object} ;
+<urn:uuid:${uuid.v4()}> a as:${activity} ;
+    as:object ${object} ;${targetLine}${stateLine}
```
Comment (csarven) [inline lib/rdf-notification-template.js:51]:
```suggestion
    as:object <${object}> ;${targetLine}${stateLine}
```

File: lib/rdf-notification-template.js [hunk 3]
```diff
@@ -13,30 +15,40 @@ function generateJSONNotification ({
...
-  target,
-  state = undefined
+  target
 }) {
-  const stateLine = `\n    notify:state "${state}" ;`
+  let targetLine = ''
+  let stateLine = ''
+
+  if (activity === 'Add') {
+    targetLine = `\n    as:target ${target} ;`
```
Comment (csarven) [inline lib/rdf-notification-template.js:37]:
```suggestion
    targetLine = `\n    as:target <${target}> ;`
```

File: lib/rdf-notification-template.js [hunk 4]
```diff
@@ -13,30 +15,40 @@ function generateJSONNotification ({
...
+  }
+  if (activity === 'Remove') {
+    targetLine = `\n    as:origin ${target} ;`
```
Comment (csarven) [inline lib/rdf-notification-template.js:40]:
```suggestion
    targetLine = `\n    as:origin <${target}> ;`
```

**Review by csarven — CHANGES_REQUESTED** [review]
I tested POST to container, PUT to non-container, and PATCH to ACL resource. The activities that are emitted seems right with the exception of some Turtle syntax corrections that are needed. See the suggestions.

I didn't run the tests.

File: lib/handlers/notify.js (hunk 1 above)
Comment (CxRes) [reply lib/handlers/notify.js:54]: Because it will not just default to but always be .000. The reason being that the time the response that triggers the notification is sent is generated internally by Node and is exposed only via the Date header on the response. And sadly HTTP date header does not have millisecond resolution.
